# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 906faf993cb59a4a030a5e133f9b5d45d21f02013d57d65ae1781e652c7ff2fdb053093092a731c31d291997920c8923cdfab8be8acb13f4e6f73336d6d640e3

test:
  secret_key_base: aee8250039dde77c03848a00ee0d552604d9e213f334391ff9b02459a5b2a2a26928d07d7ba5e59082d2d77bd56b547f05e5864e4b4ba397ab959fa96f885b9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
